### ISSUE TITLE
'grpc/support/port_platform.h' file not found

### ISSUE THREAD

**Issue by long1eu** [j0j00/flutter_liquidcore#2]
As mentioned here https://github.com/LiquidPlayer/LiquidCore/issues/102

FirebaseFirestore is not compatible with LiquidCore.
![Screenshot 2019-05-11 at 14 50 09](https://user-images.githubusercontent.com/9283414/57569353-9af1c700-73fc-11e9-83ec-65550f9f6c1a.png)

I've build a minimal, complete, and verifiable example that demonstrates it. The project has been created with flutter create and I didn't touched a thing. I just added the plugins in pubspec, added a signing team and set the min platform to 10.0.

https://github.com/long1eu/liquid_core_and_firestore_test

Any help is highly appreciated.

**Comment by wilhuff** [comment]
As I mentioned in the other issue:

Please share your project file after pod install. (Alternatively just your HEADER_SEARCH_PATHS).

Inevitably these problems happen because you have an entry in there that somehow includes your Pods folder recursively (either directly or indirectly) which allows these conflicts to occur.

Also, the full error message text from the build log rather than a screenshot would be useful.

I don't really know anything about flutter, so it's possible that your liquid_core_and_firestore_test could serve this purpose, but I have no idea how to use it to show the problem. Could you either give instructions for how to use it to show the problem or commit everything that results from pod install?

**Comment by j0j00** [comment]
Closing as it's not relevant to the flutter plugin.
